# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 02:24
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bids', models.IntegerField()),
                ('biders', models.CharField(blank=True, max_length=20)),
                ('isAuction', models.BooleanField(default=False)),
                ('duration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('to', models.CharField(max_length=20)),
                ('fromm', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=200)),
                ('timestemp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=20, null=True)),
                ('to', models.CharField(max_length=20)),
                ('fromm', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='purchaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=20)),
                ('itemname', models.CharField(max_length=50)),
                ('item_pic', models.ImageField(blank=True, upload_to='history')),
                ('price', models.CharField(max_length=50)),
                ('timestemp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SellItemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('item_name', models.CharField(max_length=25)),
                ('item_type', models.CharField(choices=[('phone', 'Phone'), ('guiter', 'Guiter'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('camera', 'Camera'), ('console', 'Console')], default='phone', max_length=6)),
                ('item_location', models.TextField()),
                ('item_lat', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('item_long', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('item_exprice', models.IntegerField()),
                ('item_usetime', models.CharField(max_length=15)),
                ('item_reason', models.TextField()),
                ('item_pic', models.ImageField(blank=True, upload_to='useritems')),
                ('likecount', models.IntegerField(default=0)),
                ('isAuction', models.BooleanField(default=False)),
                ('timestemp', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='item_likes', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='ratinginfo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.SellItemInfo'),
        ),
        migrations.AddField(
            model_name='ratinginfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.SellItemInfo'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.SellItemInfo'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctions',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.SellItemInfo'),
        ),
        migrations.AddField(
            model_name='auctions',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
